# Pandas Series

In [33]:
# create series by using list
import pandas as pd
marks= [85,90,70,65]
s= pd.Series(marks)
print(s)

0    85
1    90
2    70
3    65
dtype: int64

In [7]:
# Create series by using customise serial number
import pandas as pd
marks= [85,90,70,65]
s= pd.Series(marks, index= ['DM', 'FSD', 'COA', "TOC"])
print(s)

DM     85
FSD    90
COA    70
TOC    65
dtype: int64

In [8]:
# Create series by using tuple
import pandas as pd
t= (85,90,70,65)
s= pd.Series(t)
print(s)

0    85
1    90
2    70
3    65
dtype: int64

In [15]:
# Create series by using dict
import pandas as pd
d= {'a':10, 'b':20, 'c':30}
s= pd.Series(d)
print(s)

a    10
b    20
c    30
dtype: int64

In [18]:
# create series by using array
import numpy as np
import pandas as pd
marks= np.array([85,90,70,65])
s= pd.Series(marks)
print(s)

0    85
1    90
2    70
3    65
dtype: int32

In [20]:
# create series by using range fun
import pandas as pd
s= pd.Series(range(11,18))
print(s)

0    11
1    12
2    13
3    14
4    15
5    16
6    17
dtype: int64


# DataFrame

In [25]:
# create dataframe by using dict
import pandas as pd
data= {'name':['a','b','c'], 'marks':[100,99,98], 'City':['ahm','vad','gandhinagar']}
df=pd.DataFrame(data,index=[1,2,3])
df

  name  marks         City
1    a    100          ahm
2    b     99          vad
3    c     98  gandhinagar

In [31]:
# Create dataframe by using list
import pandas as pd
data= [['a',80],['b',90],['c',100]]
df=pd.DataFrame(data,columns=['names','marks'],index=[1,2,3])
df

  names  marks
1     a     80
2     b     90
3     c    100

In [40]:
# create dataframe by using pandas series
import pandas as pd
s1= pd.Series([1,2,3])
s2= pd.Series([8,9,10])
l={'col1':s1,'col2':s2}
df=pd.DataFrame(l)
df

   col1  col2
0     1     8
1     2     9
2     3    10

# Read CSV File

In [46]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [50]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [52]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df.head(2)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320

In [66]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [69]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df.loc[11:17]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
11,14.0,8,340.0,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400.0,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455.0,225,3086,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113.0,95,2372,15.0,70,3,toyota corona mark ii
15,22.0,6,198.0,95,2833,15.5,70,1,plymouth duster
16,18.0,6,199.0,97,2774,15.5,70,1,amc hornet
17,21.0,6,200.0,85,2587,16.0,70,1,ford maverick

In [72]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df[['mpg']]

      mpg
0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
..    ...
393  27.0
394  44.0
395  32.0
396  28.0
397  31.0

[398 rows x 1 columns]

In [75]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df[['mpg','cylinders','displacement','horsepower']].loc[21:30]

     mpg  cylinders  displacement horsepower
21  24.0          4         107.0         90
22  25.0          4         104.0         95
23  26.0          4         121.0        113
24  21.0          6         199.0         90
25  10.0          8         360.0        215
26  10.0          8         307.0        200
27  11.0          8         318.0        210
28   9.0          8         304.0        193
29  27.0          4          97.0         88
30  28.0          4         140.0         90

In [80]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df[['model year','car name']].loc[49:33:-4]

    model year                    car name
49          71          mercury capri 2000
45          71  amc hornet sportabout (sw)
41          71           plymouth fury iii
37          71                 amc matador
33          71                 amc gremlin

In [84]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df[df['cylinders']==4]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
14,24.0,4,113.0,95,2372,15.0,70,3,toyota corona mark ii
18,27.0,4,97.0,88,2130,14.5,70,3,datsun pl510
19,26.0,4,97.0,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
20,25.0,4,110.0,87,2672,17.5,70,2,peugeot 504
21,24.0,4,107.0,90,2430,14.5,70,2,audi 100 ls
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [94]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df[(df['weight']>3200)&(df['weight']<3400)]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
35,17.0,6,250.0,100,3329,15.5,71,1,chevrolet chevelle malibu
36,19.0,6,250.0,88,3302,15.5,71,1,ford torino 500
37,18.0,6,232.0,100,3288,15.5,71,1,amc matador
47,19.0,6,250.0,100,3282,15.0,71,1,pontiac firebird
98,16.0,6,250.0,100,3278,18.0,73,1,chevrolet nova custom
121,15.0,8,318.0,150,3399,11.0,73,1,dodge dart custom
128,15.0,6,250.0,100,3336,17.0,74,1,chevrolet nova
152,19.0,6,225.0,95,3264,16.0,75,1,plymouth valiant custom
165,20.0,8,262.0,110,3221,13.5,75,1,chevrolet monza 2+2
176,19.0,6,232.0,90,3211,17.0,75,1,amc pacer
191,22.0,6,225.0,100,3233,15.4,76,1,plymouth valiant
192,22.0,6,250.0,105,3353,14.5,76,1,chevrolet nova
209,19.0,4,120.0,88,3270,21.9,76,2,peugeot 504
249,19.9,8,260.0,110,3365,15.5,78,1,oldsmobile cutlass salon brougham
257,19.4,6,232.0,90,3210,17.2,78,1,amc concord
258,20.6,6,231.0,105,3380,15.8,78,1,buick century special
264,18.1,8,302.0,139,3205,11.2,78,1,ford futura
280,21.5,6,231.0,115,3245,15.4,79,1,pontiac lemans v6
283,20.2,6,232.0,90,3265,18.2,79,1,amc concord dl 6
284,20.6,6,225.0,110,3360,16.6,79,1,dodge aspen 6
316,19.1,6,225.0,90,3381,18.7,80,1,dodge aspen
328,30.0,4,146.0,67,3250,21.8,80,2,mercedes-benz 240d
359,28.1,4,141.0,80,3230,20.4,81,2,peugeot 505s turbo diesel

In [98]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df[df['horsepower']=='?']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
32,25.0,4,98.0,?,2046,19.0,71,1,ford pinto
126,21.0,6,200.0,?,2875,17.0,74,1,ford maverick
330,40.9,4,85.0,?,1835,17.3,80,2,renault lecar deluxe
336,23.6,4,140.0,?,2905,14.3,80,1,ford mustang cobra
354,34.5,4,100.0,?,2320,15.8,81,2,renault 18i
374,23.0,4,151.0,?,3035,20.5,82,1,amc concord dl

In [102]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df.shape

(398, 9)

In [104]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [106]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [122]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df.sample()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
166,13.0,8,302.0,129,3169,12.0,75,1,ford mustang ii

In [124]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df.sample(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
139,14.0,8,302.0,140,4638,16.0,74,1,ford gran torino (sw)
11,14.0,8,340.0,160,3609,8.0,70,1,plymouth 'cuda 340

In [126]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df.iloc[21:30:2,0:8:2]

     mpg  displacement  weight  model year
21  24.0         107.0    2430          70
23  26.0         121.0    2234          70
25  10.0         360.0    4615          70
27  11.0         318.0    4382          70
29  27.0          97.0    2130          71

In [129]:
import pandas as pd
df= pd.read_csv('auto-mpg.csv')
df= df[df['horsepower']!='?']
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10