# Pandas Transformation function

In [2]:
import pandas as pd 
data = {'A':[10,20,30], 'B':[5,15,25]}
df=pd.DataFrame(data)
df

    A   B
0  10   5
1  20  15
2  30  25

In [4]:
# apply()
df.apply(sum)

A    60
B    45
dtype: int64

In [5]:
df.apply(sum, axis=1)

0    15
1    35
2    55
dtype: int64

# using lambda function

In [6]:
df.apply(lambda x:x**2)

     A    B
0  100   25
1  400  225
2  900  625

# using user define function

In [11]:
def square(x):
    return x*x
def cube(x):
    return x*x*x

In [12]:
df["square"]=df['A'].apply(square)
df["cube"]=df['B'].apply(cube)
df

    A   B  square   cube
0  10   5     100    125
1  20  15     400   3375
2  30  25     900  15625

# using function parameter

In [13]:
def calc(x,a,b):
    return x*(a+b)
df['result']= df['A'].apply(calc, args=(3,4))
df

    A   B  square   cube  result
0  10   5     100    125      70
1  20  15     400   3375     140
2  30  25     900  15625     210

# astype()

In [14]:
df['result']=df['result'].astype(float)
df

    A   B  square   cube  result
0  10   5     100    125    70.0
1  20  15     400   3375   140.0
2  30  25     900  15625   210.0

# replace()

In [15]:
df.replace(10,1001)

      A   B  square   cube  result
0  1001   5     100    125    70.0
1    20  15     400   3375   140.0
2    30  25     900  15625   210.0

In [16]:
df.replace({5:50, 15:155, 25:255})

    A    B  square   cube  result
0  10   50     100    125    70.0
1  20  155     400   3375   140.0
2  30  255     900  15625   210.0

# groupby()

In [17]:
data={"Department":['IT','HR','IT','HR','Sales','IT'],
     "Employee":['A','B','C','D','E','F'],
     'Salary':[50000,45000,60000,47000,52000,70000]}
df=pd.DataFrame(data)
df

  Department Employee  Salary
0         IT        A   50000
1         HR        B   45000
2         IT        C   60000
3         HR        D   47000
4      Sales        E   52000
5         IT        F   70000

In [19]:
df.groupby('Department')['Salary'].sum()

Department
HR        92000
IT       180000
Sales     52000
Name: Salary, dtype: int64

In [24]:
df.groupby('Department')['Salary'].mean()

Department
HR       46000
IT       60000
Sales    52000
Name: Salary, dtype: int64

In [25]:
df.groupby('Department')['Salary'].median()

Department
HR       46000
IT       60000
Sales    52000
Name: Salary, dtype: int64

# multiple aggregation

In [28]:
df.groupby('Department')['Salary'].agg(['sum', 'mean', 'max'])

               sum   mean    max
Department
HR           92000  46000  47000
IT          180000  60000  70000
Sales        52000  52000  52000

# apply() for custom operation

In [29]:
df.groupby('Department')['Salary'].apply(lambda x:x.max()-x.min())

Department
HR        2000
IT       20000
Sales        0
Name: Salary, dtype: int64

# statistical summary

In [30]:
df.groupby('Department')['Salary'].describe()

,count,mean,std,min,25%,50%,75%,max
Department,,,,,,,,
HR,2.0,46000.0,1414.213562,45000.0,45500.0,46000.0,46500.0,47000.0
IT,3.0,60000.0,10000.000000,50000.0,55000.0,60000.0,65000.0,70000.0
Sales,1.0,52000.0,NaN,52000.0,52000.0,52000.0,52000.0,52000.0

In [31]:
df.groupby('Department').sample()

  Department Employee  Salary
3         HR        D   47000
5         IT        F   70000
4      Sales        E   52000

In [33]:
df.groupby('Department').size()

Department
HR       2
IT       3
Sales    1
dtype: int64

In [35]:
df.groupby('Department').nth(0)

           Employee  Salary
Department
HR                B   45000
IT                A   50000
Sales             E   52000

In [37]:
df.groupby('Department').groups

{'HR': [1, 3], 'IT': [0, 2, 5], 'Sales': [4]}

In [38]:
df.groupby('Department')['Salary'].nunique()

Department
HR       2
IT       3
Sales    1
Name: Salary, dtype: int64

# concat()

In [39]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[5,6],'B':[7,8]})
df1

   A  B
0  1  3
1  2  4

In [40]:
df2

   A  B
0  5  7
1  6  8

In [42]:
result = pd.concat([df1,df2])
result

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [43]:
result = pd.concat([df1,df2], axis=1)
result

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [44]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[5,6],'D':[7,8]})
result=pd.concat([df1,df2],join='inner') 
result

   A
0  1
1  2
0  5
1  6

In [46]:
result=pd.concat([df1,df2],join='outer')
result

   A    B    D
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

# ignore_index()

In [47]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[5,6],'D':[7,8]})
result=pd.concat([df1,df2],ignore_index='true') 
result

   A    B    D
0  1  3.0  NaN
1  2  4.0  NaN
2  5  NaN  7.0
3  6  NaN  8.0

# keys

In [50]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[5,6],'B':[7,8]})
result=pd.concat([df1,df2],keys=["train", "test"]) 
result

         A  B
train 0  1  3
      1  2  4
test  0  5  7
      1  6  8

# names

In [55]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[5,6],'B':[7,8]})
result=pd.concat([df1,df2],keys=["train", "test"],names=["Dataset"]) 
result

           A  B
Dataset
train   0  1  3
        1  2  4
test    0  5  7
        1  6  8

# verify_integrity(default=False)

In [56]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[5,6],'B':[7,8]})
result=pd.concat([df1,df2],verify_integrity=False) 
result

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

# sort()

In [57]:
df1=pd.DataFrame({'E':[1,2],'B':[3,4]})
df2=pd.DataFrame({'D':[5,6],'C':[7,8]})
result=pd.concat([df1,df2],sort=True) 
result

     B    C    D    E
0  3.0  NaN  NaN  1.0
1  4.0  NaN  NaN  2.0
0  NaN  7.0  5.0  NaN
1  NaN  8.0  6.0  NaN

# PB 63

In [60]:
# 1
df=pd.read_csv("spotify.csv")
df

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [61]:
# 2
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 17.5+ MB

In [62]:
# 3
df.describe()

,Unnamed: 0,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,56999.500000,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,32909.109681,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28499.750000,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,56999.500000,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,85499.250000,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,113999.000000,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [66]:
# 4
df.corr()

,Unnamed: 0,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
Unnamed: 0,1.000000,0.032142,-0.032743,-0.054736,0.003444,-0.055994,-0.005520,-0.027307,0.005107,-0.084952,0.076840,-0.070286,0.033639,0.053111,-0.025824,-0.021115
popularity,0.032142,1.000000,-0.007101,0.044082,0.035448,0.001056,-0.003853,0.050423,-0.013931,-0.044927,-0.025472,-0.095139,-0.005387,-0.040534,0.013205,0.031073
duration_ms,-0.032743,-0.007101,1.000000,-0.065263,-0.073426,0.058523,0.008114,-0.003470,-0.035556,-0.062600,-0.103788,0.124371,0.010321,-0.154479,0.024346,0.018225
explicit,-0.054736,0.044082,-0.065263,1.000000,0.122507,0.096955,0.004484,0.108588,-0.037212,0.307952,-0.094403,-0.103404,0.032549,-0.003381,-0.002816,0.038386
danceability,0.003444,0.035448,-0.073426,0.122507,1.000000,0.134325,0.036469,0.259077,-0.069219,0.108626,-0.171533,-0.185606,-0.131617,0.477341,-0.050450,0.207218
energy,-0.055994,0.001056,0.058523,0.096955,0.134325,1.000000,0.048006,0.761690,-0.078362,0.142509,-0.733906,-0.181879,0.184796,0.258934,0.247851,0.187126
key,-0.005520,-0.003853,0.008114,0.004484,0.036469,0.048006,1.000000,0.038590,-0.135916,0.020418,-0.040937,-0.006823,-0.001600,0.034103,0.010917,0.015065
loudness,-0.027307,0.050423,-0.003470,0.108588,0.259077,0.761690,0.038590,1.000000,-0.041764,0.060826,-0.589803,-0.433477,0.076899,0.279848,0.212446,0.191992
mode,0.005107,-0.013931,-0.035556,-0.037212,-0.069219,-0.078362,-0.135916,-0.041764,1.000000,-0.046532,0.095553,-0.049955,0.014012,0.021953,0.000566,-0.024092
speechiness,-0.084952,-0.044927,-0.062600,0.307952,0.108626,0.142509,0.020418,0.060826,-0.046532,1.000000,-0.002186,-0.089616,0.205219,0.036635,0.017273,-0.000011
acousticness,0.076840,-0.025472,-0.103788,-0.094403,-0.171533,-0.733906,-0.040937,-0.589803,0.095553,-0.002186,1.000000,0.104027,-0.020700,-0.107070,-0.208224,-0.176138
instrumentalness,-0.070286,-0.095139,0.124371,-0.103404,-0.185606,-0.181879,-0.006823,-0.433477,-0.049955,-0.089616,0.104027,1.000000,-0.079893,-0.324312,-0.050330,-0.082580
liveness,0.033639,-0.005387,0.010321,0.032549,-0.131617,0.184796,-0.001600,0.076899,0.014012,0.205219,-0.020700,-0.079893,1.000000,0.019086,0.000600,-0.023651
valence,0.053111,-0.040534,-0.154479,-0.003381,0.477341,0.258934,0.034103,0.279848,0.021953,0.036635,-0.107070,-0.324312,0.019086,1.000000,0.078273,0.133686
tempo,-0.025824,0.013205,0.024346,-0.002816,-0.050450,0.247851,0.010917,0.212446,0.000566,0.017273,-0.208224,-0.050330,0.000600,0.078273,1.000000,0.066641
time_signature,-0.021115,0.031073,0.018225,0.038386,0.207218,0.187126,0.015065,0.191992,-0.024092,-0.000011,-0.176138,-0.082580,-0.023651,0.133686,0.066641,1.000000

In [67]:
# 5
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [71]:
# 6
df.tail()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.235,...,-16.393,1,0.0422,0.640,0.928,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.117,...,-18.318,0,0.0401,0.994,0.976,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.329,...,-10.895,0,0.0420,0.867,0.000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.506,...,-10.889,1,0.0297,0.381,0.000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.487,...,-10.204,0,0.0725,0.681,0.000,0.0893,0.7080,79.198,4,world-music

In [72]:
# 7
df.iloc[16:39]

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
16,16,6xKeQgzfjixSUld14qUezm,Andrew Foy;Renee Foy,ily (i love you baby),ily (i love you baby),56,129750,False,0.706,0.1120,...,-18.098,1,0.0391,0.8270,0.000004,0.1250,0.4140,110.154,4,acoustic
17,17,4Yo0igmcoNyat1secaH0OD,Andrew Foy;Renee Foy,At My Worst,At My Worst,54,169728,False,0.795,0.0841,...,-18.090,0,0.0461,0.7420,0.000012,0.0853,0.6090,91.803,4,acoustic
18,18,2qLMf6TuEC3ruGJg4SMMN6,Jason Mraz;Colbie Caillat,We Sing. We Dance. We Steal Things.,Lucky,68,189613,False,0.625,0.4140,...,-8.700,1,0.0369,0.2940,0.000000,0.1510,0.6690,130.088,4,acoustic
19,19,6CgNoAbFJ4Q4Id4EjtbXlC,Boyce Avenue;Bea Miller,"Cover Sessions, Vol. 4",Photograph,67,260186,False,0.717,0.3200,...,-8.393,1,0.0283,0.8300,0.000000,0.1070,0.3220,107.946,4,acoustic
20,20,3S0OXQeoh0w6AY8WQVckRW,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,75,242946,False,0.703,0.4440,...,-9.331,1,0.0417,0.5590,0.000000,0.0973,0.7120,150.960,4,acoustic
21,21,210JCw2LbYD4YIs8GiZ9iP,Boyce Avenue;Jennel Garcia,"Cover Sessions, Vol. 3",Demons,63,174174,False,0.678,0.3510,...,-8.654,1,0.0266,0.7470,0.000000,0.3550,0.5690,90.032,4,acoustic
22,22,5TvE3pk05pyFIGdSY9j4DJ,A Great Big World;Christina Aguilera,Is There Anybody Out There? - Track by Track C...,Say Something,70,229400,False,0.407,0.1470,...,-8.822,1,0.0355,0.8570,0.000003,0.0913,0.0765,141.284,3,acoustic
23,23,0BUuuEvNa5T4lMaewyiudB,Jason Mraz,Coffee Moment,93 Million Miles,0,216386,False,0.572,0.4540,...,-10.286,1,0.0258,0.4770,0.000014,0.0974,0.5150,140.182,4,acoustic
24,24,3Hn3LfhrQOaKihdCibJsTs,Jason Mraz,Human - Best Adult Pop Tunes,Unlonely,0,231266,False,0.796,0.6670,...,-4.831,0,0.0392,0.3810,0.000000,0.2210,0.7540,97.988,4,acoustic
25,25,6D33wCKzWtNEgOovgeVJ7r,Jason Mraz,Mellow Adult Pop,Bella Luna,1,302346,False,0.755,0.4540,...,-9.609,0,0.0352,0.7570,0.000000,0.2360,0.3300,120.060,4,acoustic
26,26,5IfCZDRXZrqZSm8AwE44PG,Jason Mraz,Holly Jolly Christmas,Winter Wonderland,0,131760,False,0.620,0.3090,...,-9.209,1,0.0495,0.7880,0.000000,0.1460,0.6640,145.363,4,acoustic
27,27,0dzKBptH2P5j5a0MifBMwM,Jason Mraz,Feeling Good - Adult Pop Favorites,If It Kills Me,0,273653,False,0.633,0.4290,...,-6.784,0,0.0381,0.0444,0.000000,0.1320,0.5200,143.793,4,acoustic
28,28,5QAMZTM5cmLg3fHX9ZbTZi,Jason Mraz,Christmas Time,Winter Wonderland,0,131760,False,0.620,0.3090,...,-9.209,1,0.0495,0.7880,0.000000,0.1460,0.6640,145.363,4,acoustic
29,29,2qESE1ZeWly7I3YjyTXmXh,Jason Mraz,Perfect Christmas Hits,Winter Wonderland,0,131760,False,0.620,0.3090,...,-9.209,1,0.0495,0.7880,0.000000,0.1460,0.6640,145.363,4,acoustic
30,30,3EQV1ZHtHvq9OnVRYIdbg3,Jason Mraz,Merry Christmas,Winter Wonderland,0,131760,False,0.620,0.3090,...,-9.209,1,0.0495,0.7880,0.000000,0.1460,0.6640,145.363,4,acoustic
31,31,3ax0rfGb7exLtl02LL08U9,Jason Mraz,Christmas Music - Holiday Hits,Winter Wonderland,0,131760,False,0.620,0.3090,...,-9.209,1,0.0495,0.7880,0.000000,0.1460,0.6640,145.363,4,acoustic
32,32,1m5LC29RE52Bxy7hxvpOlL,Chord Overstreet,Christmas Country Songs 2022,All I Want For Christmas Is A Real Good Tan,0,234186,False,0.593,0.4550,...,-8.192,1,0.0388,0.3660,0.000000,0.0914,0.5640,202.019,4,acoustic
33,33,3H36x7buZdQD4687VmFrwY,Brandi Carlile;Sam Smith,Human - Best Adult Pop Tunes,Party of One,0,259558,False,0.296,0.2060,...,-11.799,1,0.0412,0.7820,0.000225,0.0959,0.2020,165.400,4,acoustic
34,34,0xbMRcMFqxJq1Wa7tvWPtn,Brandi Carlile;Sam Smith,Feeling Good - Adult Pop Favorites,Party of One,0,259558,False,0.296,0.2060,...,-11.799,1,0.0412,0.7820,0.000225,0.0959,0.2020,165.400,4,acoustic
35,35,6h061f44HZPj1OXO2nA45d,Brandi Carlile;Sam Smith,Mellow Bars R'n'B,Party of One,0,259558,False,0.296,0.2060,...,-11.799,1,0.0412,0.7820,0.000225,0.0959,0.2020,165.400,4,acoustic
36,36,62EwQLDw0dprDzuLwQ0sH1,KT Tunstall,Chill Christmas Dinner,Lonely This Christmas,0,257493,False,0.409,0.1530,...,-10.740,0,0.0306,0.9390,0.000026,0.1080,0.1800,85.262,4,acoustic
37,37,3lvo0I8c2qBJDLZWqExDgC,Brandi Carlile,rainy day indie,Throwing Good After Bad,0,247791,False,0.501,0.0952,...,-12.931,1,0.0540,0.9630,0.000016,0.0915,0.3160,138.016,4,acoustic
38,38,1ae8XfBQ3fDEvmBjFaemGV,Brandi Carlile,Coffee Moment,This Time Tomorrow,0,206267,False,0.606,0.3260,...,-10.031,1,0.0294,0.8410,0.000000,0.1390,0.4140,91.626,4,acoustic

In [74]:
# 8
df.iloc[-5:, -5:]

        liveness  valence    tempo  time_signature  track_genre
113995    0.0863   0.0339  125.995               5  world-music
113996    0.1050   0.0350   85.239               4  world-music
113997    0.0839   0.7430  132.378               4  world-music
113998    0.2700   0.4130  135.960               4  world-music
113999    0.0893   0.7080   79.198               4  world-music

In [75]:
# 9
df.shape

(114000, 21)

In [76]:
# 10
df.isnull().sum()

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [83]:
# 11
df.drop(columns=['Unnamed: 0', 'track_id', 'artists'], inplace=True)

In [84]:
df

,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,Change Your World,Friends,41,283893,False,0.587,0.5060,7,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [85]:
# 12
df.drop(range(0,10),inplace=True)

In [86]:
df

,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
10,Episode,Give Me Your Forever,74,244800,False,0.627,0.363,8,-8.127,1,0.0291,0.279,0.000000,0.0928,0.3010,99.905,4,acoustic
11,Love Is a Four Letter Word,I Won't Give Up,69,240165,False,0.483,0.303,4,-10.058,1,0.0429,0.694,0.000000,0.1150,0.1390,133.406,3,acoustic
12,Solo,Solo,52,198712,False,0.489,0.314,7,-9.245,0,0.0331,0.749,0.000000,0.1130,0.6070,124.234,4,acoustic
13,Bad Liar,Bad Liar,62,248448,False,0.691,0.234,3,-6.441,1,0.0285,0.777,0.000000,0.1200,0.2090,87.103,4,acoustic
14,Hold On (Remix),Hold On - Remix,56,188133,False,0.755,0.780,2,-6.084,1,0.0327,0.124,0.000028,0.1210,0.3870,120.004,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.235,5,-16.393,1,0.0422,0.640,0.928000,0.0863,0.0339,125.995,5,world-music
113996,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.117,0,-18.318,0,0.0401,0.994,0.976000,0.1050,0.0350,85.239,4,world-music
113997,Best Of,Miss Perfumado,22,271466,False,0.629,0.329,0,-10.895,0,0.0420,0.867,0.000000,0.0839,0.7430,132.378,4,world-music
113998,Change Your World,Friends,41,283893,False,0.587,0.506,7,-10.889,1,0.0297,0.381,0.000000,0.2700,0.4130,135.960,4,world-music
113999,Miss Perfumado,Barbincor,22,241826,False,0.526,0.487,1,-10.204,0,0.0725,0.681,0.000000,0.0893,0.7080,79.198,4,world-music

In [94]:
# 13
Q1 = df['popularity'].quantile(0.25)
Q3 = df['popularity'].quantile(0.75)
IQR = Q3 - Q1

outliers_popularity = df[(df['popularity'] < Q1 - 1.5*IQR) | (df['popularity'] > Q3 + 1.5*IQR)]

print("\nOutliers in popularity column:")
outliers_popularity

Outliers in popularity column:

,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
20001,Unholy (feat. Kim Petras),Unholy (feat. Kim Petras),100,156943,False,0.714,0.472,2,-7.375,1,0.0864,0.013,0.000005,0.266,0.238,131.121,4,dance
81051,Unholy (feat. Kim Petras),Unholy (feat. Kim Petras),100,156943,False,0.714,0.472,2,-7.375,1,0.0864,0.013,0.000005,0.266,0.238,131.121,4,pop

In [95]:
# 14
Q1 = df['energy'].quantile(0.25)
Q3 = df['energy'].quantile(0.75)
IQR = Q3 - Q1

df_no_outliers = df[(df['energy'] >= Q1 - 1.5*IQR) & (df['energy'] <= Q3 + 1.5*IQR)]

print("\nDataFrame after removing energy outliers:")
df_no_outliers

DataFrame after removing energy outliers:

,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
10,Episode,Give Me Your Forever,74,244800,False,0.627,0.363,8,-8.127,1,0.0291,0.279,0.000000,0.0928,0.3010,99.905,4,acoustic
11,Love Is a Four Letter Word,I Won't Give Up,69,240165,False,0.483,0.303,4,-10.058,1,0.0429,0.694,0.000000,0.1150,0.1390,133.406,3,acoustic
12,Solo,Solo,52,198712,False,0.489,0.314,7,-9.245,0,0.0331,0.749,0.000000,0.1130,0.6070,124.234,4,acoustic
13,Bad Liar,Bad Liar,62,248448,False,0.691,0.234,3,-6.441,1,0.0285,0.777,0.000000,0.1200,0.2090,87.103,4,acoustic
14,Hold On (Remix),Hold On - Remix,56,188133,False,0.755,0.780,2,-6.084,1,0.0327,0.124,0.000028,0.1210,0.3870,120.004,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.235,5,-16.393,1,0.0422,0.640,0.928000,0.0863,0.0339,125.995,5,world-music
113996,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.117,0,-18.318,0,0.0401,0.994,0.976000,0.1050,0.0350,85.239,4,world-music
113997,Best Of,Miss Perfumado,22,271466,False,0.629,0.329,0,-10.895,0,0.0420,0.867,0.000000,0.0839,0.7430,132.378,4,world-music
113998,Change Your World,Friends,41,283893,False,0.587,0.506,7,-10.889,1,0.0297,0.381,0.000000,0.2700,0.4130,135.960,4,world-music
113999,Miss Perfumado,Barbincor,22,241826,False,0.526,0.487,1,-10.204,0,0.0725,0.681,0.000000,0.0893,0.7080,79.198,4,world-music

In [93]:
# 15
pd.crosstab(df['time_signature'], df['track_genre'])

track_genre,acoustic,afrobeat,alt-rock,alternative,ambient,anime,black-metal,bluegrass,blues,brazil,...,spanish,study,swedish,synth-pop,tango,techno,trance,trip-hop,turkish,world-music
time_signature,,,,,,,,,,,,,,,,,,,,,
0,0,0,1,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,3
1,9,5,1,2,39,7,20,5,6,5,...,2,6,6,2,17,3,5,7,3,7
3,99,52,56,64,264,63,129,80,97,42,...,55,49,49,16,167,26,37,38,75,132
4,869,930,940,922,648,923,838,909,894,939,...,937,934,928,981,784,969,949,951,909,844
5,13,13,2,12,46,7,13,6,3,14,...,6,11,17,1,32,2,9,4,12,14