# merge Dataframe

In [2]:
import pandas as pd 
employee = pd.DataFrame({'emp_id':[1,2,3],
                        'name':['A','B','C'],
                        'dept_id':[10,20,30]})
department = pd.DataFrame({'dept_id':[10,20,40],
                          'dept_name':['HR','IT','Finance']})
pd.merge(employee, department, on='dept_id', how='inner')

   emp_id name  dept_id dept_name
0       1    A       10        HR
1       2    B       20        IT

In [3]:
pd.merge(employee, department, on='dept_id', how='outer')

   emp_id name  dept_id dept_name
0     1.0    A       10        HR
1     2.0    B       20        IT
2     3.0    C       30       NaN
3     NaN  NaN       40   Finance

In [4]:
pd.merge(employee, department, on='dept_id', how='left')

   emp_id name  dept_id dept_name
0       1    A       10        HR
1       2    B       20        IT
2       3    C       30       NaN

In [5]:
pd.merge(employee, department, on='dept_id', how='right')

   emp_id name  dept_id dept_name
0     1.0    A       10        HR
1     2.0    B       20        IT
2     NaN  NaN       40   Finance

# left_on & right_on

In [8]:
employee = pd.DataFrame({'emp_id':[1,2],
                        'name':['A','B'],
                        'dept_id':[10,20]})
department = pd.DataFrame({'d_id':[10,20],
                          'dept_name':['HR','IT']})
pd.merge(employee, department, left_on="dept_id", right_on="d_id")

   emp_id name  dept_id  d_id dept_name
0       1    A       10    10        HR
1       2    B       20    20        IT

# left_index & right_index

In [11]:
pd.merge(employee, department, left_index=True, right_index=True)

   emp_id name  dept_id  d_id dept_name
0       1    A       10    10        HR
1       2    B       20    20        IT

# suffixes

In [14]:
employee = pd.DataFrame({'emp_id':[1,2],
                        'name':['A','B'],
                        'dept_id':[10,20]})
department = pd.DataFrame({'dept_id':[10,20],
                          'dept_name':['HR','IT'],
                          'name':['X','Y']})
pd.merge(employee, department, on="dept_id", suffixes=('_emp','_dept'))

   emp_id name_emp  dept_id dept_name name_dept
0       1        A       10        HR         X
1       2        B       20        IT         Y

# indicator

In [15]:
employee = pd.DataFrame({'emp_id':[1,2,3],
                        'name':['A','B','C'],
                        'dept_id':[10,20,30]})
department = pd.DataFrame({'dept_id':[10,20,40],
                          'dept_name':['HR','IT','Finance']})
pd.merge(employee, department, on='dept_id', how='outer', indicator= True)

   emp_id name  dept_id dept_name      _merge
0     1.0    A       10        HR        both
1     2.0    B       20        IT        both
2     3.0    C       30       NaN   left_only
3     NaN  NaN       40   Finance  right_only