In [2]:
# KNN

# PB 268

In [20]:
import pandas as pd

In [21]:
df= pd.read_csv('data_breast_cancer.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [22]:
df.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [23]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [24]:
df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [25]:
y=df['diagnosis']
x=df[['radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst']]

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [27]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(455, 30)
(114, 30)
(455,)
(114,)

In [28]:
from sklearn.neighbors import KNeighborsClassifier
nn= KNeighborsClassifier(n_neighbors=21)

In [29]:
model = nn.fit(x_train, y_train)

In [30]:
y_pred= model.predict(x_test)
y_pred

array(['B', 'M', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'B',
       'M', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M',
       'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B',
       'B', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'M', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'M'], dtype=object)

In [31]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[71,  0],
       [ 4, 39]])

In [32]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]

In [33]:
accuracy = (TP+TN)/(TP+TN+FP+FN)
error_rate = (FP+FN)/(TP+TN+FP+FN) 
sensitivity = TP/(TP+FN)
specificity = TN/(TN+FP)

print('accuracy =',accuracy)
print('error rate =',error_rate)
print('sensitivity =',sensitivity)
print('specificity =',specificity)

accuracy = 0.9649122807017544
error rate = 0.03508771929824561
sensitivity = 0.9069767441860465
specificity = 1.0

# PB 271

In [34]:
df1= pd.read_csv('PlayTennis.csv')
df1.head()

    outlook  temp humidity  windy play
0     sunny   hot     high  False   no
1     sunny   hot     high   True   no
2  overcast   hot     high  False  yes
3     rainy  mild     high  False  yes
4     rainy  cool   normal  False  yes

In [35]:
df1.isna().sum()

outlook     0
temp        0
humidity    0
windy       0
play        0
dtype: int64

In [36]:
df1= pd.get_dummies(data=df1, drop_first=True)
df1.head()

,windy,outlook_rainy,outlook_sunny,temp_hot,temp_mild,humidity_normal,play_yes
0,False,False,True,True,False,False,False
1,True,False,True,True,False,False,False
2,False,False,False,True,False,False,True
3,False,True,False,False,True,False,True
4,False,True,False,False,False,True,True

In [37]:
y1=df1['play_yes']
x1=df1[['windy', 'outlook_rainy', 'outlook_sunny', 'temp_hot', 'temp_mild', 'humidity_normal']]

In [38]:
from sklearn.model_selection import train_test_split
x_train1, x_test1, y_train1, y_test1 = train_test_split(x1,y1,test_size=0.2,random_state=42)

In [40]:
print(x_train1.shape)
print(x_test1.shape)
print(y_train1.shape)
print(y_test1.shape)

(11, 6)
(3, 6)
(11,)
(3,)

In [41]:
from sklearn.neighbors import KNeighborsClassifier
nn= KNeighborsClassifier(n_neighbors=3)

In [42]:
model1 = nn.fit(x_train1, y_train1)

In [44]:
y_pred1= model1.predict(x_test1)
y_pred1

array([ True, False,  True])

In [45]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test1,y_pred1)
cm1

array([[0, 1],
       [1, 1]])

In [46]:
TN=cm1[0][0]
FP=cm1[0][1]
FN=cm1[1][0]
TP=cm1[1][1]

In [47]:
accuracy = (TP+TN)/(TP+TN+FP+FN)
error_rate = (FP+FN)/(TP+TN+FP+FN) 
sensitivity = TP/(TP+FN)
specificity = TN/(TN+FP)

print('accuracy =',accuracy)
print('error rate =',error_rate)
print('sensitivity =',sensitivity)
print('specificity =',specificity)

accuracy = 0.3333333333333333
error rate = 0.6666666666666666
sensitivity = 0.5
specificity = 0.0

In [48]:
# rainy, cool, high humidity, windy
model1.predict([[1,1,0,0,0,0]])

C:\ProgramData\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([False])

In [50]:
# new programm 
df= pd.read_csv('Fish.csv')
df.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [51]:
y= df['Species']
x= df[['Weight','Length1', 'Length2', 'Length3', 'Height', 'Width']]

In [52]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [53]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(127, 6)
(32, 6)
(127,)
(32,)

In [54]:
from sklearn.neighbors import KNeighborsClassifier
nn= KNeighborsClassifier(n_neighbors=11)

In [55]:
model = nn.fit(x_train, y_train)

In [56]:
y_pred= model.predict(x_test)
y_pred

array(['Perch', 'Smelt', 'Roach', 'Perch', 'Roach', 'Perch', 'Smelt',
       'Roach', 'Roach', 'Perch', 'Bream', 'Perch', 'Bream', 'Roach',
       'Bream', 'Perch', 'Perch', 'Perch', 'Perch', 'Bream', 'Smelt',
       'Bream', 'Bream', 'Bream', 'Perch', 'Perch', 'Roach', 'Perch',
       'Smelt', 'Smelt', 'Bream', 'Perch'], dtype=object)

In [57]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[7, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 6, 0, 3, 0, 0],
       [1, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 3, 0, 0, 0, 0]])

In [58]:
model.predict([[85,25,20,31,6,2.5]])

C:\ProgramData\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array(['Perch'], dtype=object)

In [59]:
# new programm
df=pd.read_csv('Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [60]:
x=df[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y=df['Species']

In [61]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [62]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(80, 4)
(21, 4)
(80,)
(21,)

In [63]:
from sklearn.neighbors import KNeighborsClassifier
nn= KNeighborsClassifier(n_neighbors=9)

In [64]:
model = nn.fit(x_train, y_train)

In [65]:
y_pred= model.predict(x_test)
y_pred

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor'], dtype=object)

In [66]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[12,  0],
       [ 0,  9]])

In [67]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]

In [68]:
accuracy = (TP+TN)/(TP+TN+FP+FN)
error_rate = (FP+FN)/(TP+TN+FP+FN) 
sensitivity = TP/(TP+FN)
specificity = TN/(TN+FP)

print('accuracy =',accuracy)
print('error rate =',error_rate)
print('sensitivity =',sensitivity)
print('specificity =',specificity)

accuracy = 1.0
error rate = 0.0
sensitivity = 1.0
specificity = 1.0

# PB 230

In [70]:
df = pd.read_csv('windpower.csv')
df.head()

   Power (kW)  Wind speed (m/s)
0         0.0             0.000
1         0.0             0.125
2         0.0             0.150
3         0.0             0.225
4         0.0             0.275

In [72]:
df.isna().sum()

Power (kW)          3
Wind speed (m/s)    5
dtype: int64

In [75]:
df.dropna(inplace=True)

In [76]:
y=df['Power (kW)']
x=df[['Wind speed (m/s)']]